name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16.x
  HUSKY: 0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Save node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Lint
        run: yarn lint

      - name: Code formmating check
        run: yarn format:check

      - name: Build
        run: yarn build

      - name: Unit tests
        run: yarn test

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-report
          path: reports/jest

      - name: Upload Coverage reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: reports/coverage/lcov-report

  release:
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          registry-url: "https://registry.npmjs.org"
          scope: "@brpaz"
          always-auth: true

      - name: Restore node_modules cache
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Set git identitiy
        run: |
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Publish to NPM
        run: yarn publish --access public --non-interactive --new-version ${RELEASE_TAG}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Authenticate on GitHub package registry
        run: |
          echo "@brpaz:registry=https://npm.pkg.github.com" >> .npmrc
          echo "https://npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: yarn publish --access public --non-interactive  --non-interactive --new-version ${RELEASE_TAG}

      - name: Update version in package.json
        run: npm version ${RELEASE_TAG} --force --no-git-tag-version

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated Changelog and Package.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "chore(release): [skip ci] bump version ${RELEASE_TAG}"
          file_pattern: "CHANGELOG.md package.json"
